### ISSUE TITLE
Could not find a version of package

### ISSUE THREAD

**Issue by martijnvanonz** [sjelfull/craft3-publishedevent#2]
Hello,

I get this error when i try to install the plugin.
Hope you could help me. 

[InvalidArgumentException]                                                                                                                                                                   
  Could not find a version of package superbig/craft3-publishedevent matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.

**Comment by sjelfull** [comment]
This hasn't been published on Packagist because I haven't got time right now.

Might have some time over the holidays.

**Comment by sanscheese** [comment]
Just checking if this project is still on the radar?

**Comment by sjelfull** [comment]
P&T has plans to introduce programmatic scheduling into Craft and solve this, so not a big priority.

**Comment by sanscheese** [comment]
Makes sense. Cheers for update.
